name: deploy
on:
  push:
    branches:
      - main

env:
  APP_DIR_ROOT: ${{ secrets.APP_DIR_ROOT }}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: remote ssh rebase
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.KEY }}
          envs: APP_DIR_ROOT
          script: |
            cd $APP_DIR_ROOT
            git fetch
            git rebase origin/main